Ethantr/feature/unavailability form testing
TechlauncherFireApp/FireApp-Mobile pull request #70
Opened 2024-04-11 07:57 UTC by ethantr

## Describe your changes
Unit tests for the unavailability form view model have been made. 

1. The unit tests check to see if the fields (title, date fields) can be updated and match their input.
2. It checks to see if an exception is raised if the end date is before the start date.
3. It checks if the form is "valid" (all fields filled) logic is correct.
4. It also checks if dispose works.

Next: data layer - repository and client

## Issue ticket number and link
FE-181

2024-04-11 09:23 UTC, emilymclean requested changes
Great work, just one minor change and I'll approve :)

2024-04-11 09:23 UTC, emilymclean commented on fireapp/test/presentation/unavailability_form/unavailability_form_view_model_test.dart
> +@GenerateMocks([AuthenticationRepository, UnavailabilityFormRepository])
I typically put this above the import statement for said mocks (i.e, put it above line 13)

2024-04-11 09:48 UTC, ethantr commented on fireapp/test/presentation/unavailability_form/unavailability_form_view_model_test.dart
> +@GenerateMocks([AuthenticationRepository, UnavailabilityFormRepository])
is that what you mean?

2024-04-11 23:37 UTC, emilymclean commented on fireapp/test/presentation/unavailability_form/unavailability_form_view_model_test.dart
> +@GenerateMocks([AuthenticationRepository, UnavailabilityFormRepository])
Like directly above

```
@GenerateMocks([AuthenticationRepository, UnavailabilityFormRepository])
import 'unavailability_form_view_model_test.mocks.dart';
```

2024-04-12 08:38 UTC, BenMMcLean approved these changes

2024-04-12 08:44 UTC, merged