Home page ViewModel
TechlauncherFireApp/FireApp-Mobile pull request #96
Opened 2024-08-24 12:30 UTC by TaiHaDev

## Describe your changes

- Added logic for shifts fetching and dummy data for testing and visualisation
- Merged main branch to get the view and made it compatible
<img width="273" alt="image" src="https://github.com/user-attachments/assets/df870252-23c7-4c00-be77-cdac369b628c">

2024-08-24 12:43 UTC, BenMMcLean requested changes
Looks good, just a couple of quick changes before I approve.

2024-08-24 12:43 UTC, BenMMcLean commented on fireapp/lib/presentation/volunteer_home/volunteer_home_view_model.dart
> +    _loadingState.add(RequestState.loading());
You should be setting `_shifts` to `RequestState.loading()`, not this. Each RequestState stream is supposed to represent the lifecycle of a *single* operation (fetching some kind of data, posting a form, etc), so splitting it across multiple states isn't good practice. `_loadingState` isn't actually used here, so I'd appreciate it if you just deleted it completely.

2024-08-24 12:43 UTC, BenMMcLean commented on fireapp/lib/presentation/volunteer_home/volunteer_home_view_model.dart
> +      await _shiftsRepository.getVolunteerShifts(userID);
Please indent this

2024-08-28 02:40 UTC, TaiHaDev commented
Hi @BenMMcLean, I have committed your suggested changes. Can you take a look?👀

2024-08-28 03:23 UTC, BenMMcLean approved these changes, later dismissed

2024-08-28 03:25 UTC, BenMMcLean approved these changes

2024-08-28 03:25 UTC, merged